# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 12 May 2017 13:54:48 +0000
*	@ALL	1
board_member_notebook	@user	1
board_member_notebook	@ALL	0
board_member_notebook	@board	1
