<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Mon, 11 Apr 2016 11:07:33 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
